/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    barrel_03: THREE.Mesh
  }
  materials: {
    barrel_03: THREE.MeshStandardMaterial
  }
}

export function Barrel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/Barrel.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.barrel_03.geometry} material={materials.barrel_03} />
    </group>
  )
}

useGLTF.preload('/glbs/Barrel.glb')
