/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    dry_branches_medium_01_c: THREE.Mesh
    dry_branches_medium_01_b: THREE.Mesh
    dry_branches_medium_01_a: THREE.Mesh
  }
  materials: {
    dry_branches_medium_01: THREE.MeshStandardMaterial
  }
}

export function Branches(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/Branches.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dry_branches_medium_01_c.geometry} material={materials.dry_branches_medium_01} position={[0.45, 0.05, -0.05]} />
      <mesh geometry={nodes.dry_branches_medium_01_b.geometry} material={materials.dry_branches_medium_01} position={[0.02, 0.06, -0.06]} />
      <mesh geometry={nodes.dry_branches_medium_01_a.geometry} material={materials.dry_branches_medium_01} position={[-0.41, 0.12, -0.06]} />
    </group>
  )
}

useGLTF.preload('/glbs/Branches.glb')
