/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere: THREE.Mesh
    Sphere_1: THREE.Mesh
    Sphere_2: THREE.Mesh
    Sphere_3: THREE.Mesh
    Sphere_4: THREE.Mesh
    Sphere_5: THREE.Mesh
    Sphere_6: THREE.Mesh
  }
  materials: {
    metal: THREE.MeshStandardMaterial
    Woodenbeams: THREE.MeshStandardMaterial
    Rock: THREE.MeshStandardMaterial
    Woodshingles: THREE.MeshStandardMaterial
    Mainwoodplanks: THREE.MeshStandardMaterial
    Window: THREE.MeshStandardMaterial
    ['Wooden door']: THREE.MeshStandardMaterial
  }
}

export function House(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/House.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.05, 0, 0.42]} scale={0.009}>
        <mesh geometry={nodes.Sphere.geometry} material={materials.metal} />
        <mesh geometry={nodes.Sphere_1.geometry} material={materials.Woodenbeams} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials.Rock} />
        <mesh geometry={nodes.Sphere_3.geometry} material={materials.Woodshingles} />
        <mesh geometry={nodes.Sphere_4.geometry} material={materials.Mainwoodplanks} />
        <mesh geometry={nodes.Sphere_5.geometry} material={materials.Window} />
        <mesh geometry={nodes.Sphere_6.geometry} material={materials['Wooden door']} />
      </group>
    </group>
  )
}

useGLTF.preload('/glbs/House.glb')
