/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Lantern_01: THREE.Mesh
    Lantern_01_glass: THREE.Mesh
  }
  materials: {
    Lantern_01_brass: THREE.MeshStandardMaterial
    Lantern_01_glass: THREE.MeshStandardMaterial
  }
}

export function Lantern(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/Lantern.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lantern_01.geometry} material={materials.Lantern_01_brass} />
      <mesh geometry={nodes.Lantern_01_glass.geometry} material={materials.Lantern_01_glass} />
    </group>
  )
}

useGLTF.preload('/glbs/Lantern.glb')
