/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    small_oil_can_01: THREE.Mesh
  }
  materials: {
    small_oil_can_01: THREE.MeshStandardMaterial
  }
}

export function Oil_Can(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/Oil_Can.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.small_oil_can_01.geometry} material={materials.small_oil_can_01} />
    </group>
  )
}

useGLTF.preload('/glbs/Oil_Can.glb')
