/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    rock_moss_set_01_rock01: THREE.Mesh
    rock_moss_set_01_rock02: THREE.Mesh
    rock_moss_set_01_rock03: THREE.Mesh
    rock_moss_set_01_rock04: THREE.Mesh
    rock_moss_set_01_rock05: THREE.Mesh
    rock_moss_set_01_rock06: THREE.Mesh
  }
  materials: {
    ['rock_moss_set_01.001']: THREE.MeshStandardMaterial
  }
}

export function Rocks(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/Rocks.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rock_moss_set_01_rock01.geometry} material={materials['rock_moss_set_01.001']} position={[-2.8, 0, -2.12]} />
      <mesh geometry={nodes.rock_moss_set_01_rock02.geometry} material={materials['rock_moss_set_01.001']} position={[0, 0, -2.12]} />
      <mesh geometry={nodes.rock_moss_set_01_rock03.geometry} material={materials['rock_moss_set_01.001']} position={[3, 0, -2.12]} />
      <mesh geometry={nodes.rock_moss_set_01_rock04.geometry} material={materials['rock_moss_set_01.001']} position={[-2.7, 0, 1.58]} />
      <mesh geometry={nodes.rock_moss_set_01_rock05.geometry} material={materials['rock_moss_set_01.001']} position={[0.15, 0, 1.48]} />
      <mesh geometry={nodes.rock_moss_set_01_rock06.geometry} material={materials['rock_moss_set_01.001']} position={[2.8, 0, 1.58]} />
    </group>
  )
}

useGLTF.preload('/glbs/Rocks.glb')
