/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    rock_moss_set_02_rock08: THREE.Mesh
    rock_moss_set_02_rock09: THREE.Mesh
    rock_moss_set_02_rock12: THREE.Mesh
    rock_moss_set_02_rock13: THREE.Mesh
    rock_moss_set_02_rock10: THREE.Mesh
    rock_moss_set_02_rock11: THREE.Mesh
    rock_moss_set_02_rock07: THREE.Mesh
  }
  materials: {
    rock_moss_set_02: THREE.MeshStandardMaterial
  }
}

export function Rocks_2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/Rocks_2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rock_moss_set_02_rock08.geometry} material={materials.rock_moss_set_02} position={[-0.97, 0, 0.73]} />
      <mesh geometry={nodes.rock_moss_set_02_rock09.geometry} material={materials.rock_moss_set_02} position={[0.85, 0, 0.73]} />
      <mesh geometry={nodes.rock_moss_set_02_rock12.geometry} material={materials.rock_moss_set_02} position={[0.16, 0, -0.96]} />
      <mesh geometry={nodes.rock_moss_set_02_rock13.geometry} material={materials.rock_moss_set_02} position={[2.67, 0.34, -0.56]} />
      <mesh geometry={nodes.rock_moss_set_02_rock10.geometry} material={materials.rock_moss_set_02} position={[3.33, 0, 0.73]} />
      <mesh geometry={nodes.rock_moss_set_02_rock11.geometry} material={materials.rock_moss_set_02} position={[-2.12, 0, -0.96]} />
      <mesh geometry={nodes.rock_moss_set_02_rock07.geometry} material={materials.rock_moss_set_02} position={[-2.92, 0.23, 0.73]} scale={0.68} />
    </group>
  )
}

useGLTF.preload('/glbs/Rocks_2.glb')
