/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SpiderRock02: THREE.Mesh
  }
  materials: {
    SpiderRock02_Base: THREE.MeshStandardMaterial
  }
}

export function SpiderRock(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glbs/SpiderRock.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SpiderRock02.geometry} material={materials.SpiderRock02_Base} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/glbs/SpiderRock.glb')
